server {
    listen 8080;
    server_name localhost;

    root /home/yel-guad/Desktop/webserv/webserv_root;

    location / {
        allowed_methods GET;
    }

    location /html {
        allowed_methods GET;
    }

    location /upload {
        allowed_methods POST;
    }

    location /cgi-bin {
        cgi .py /usr/bin/python3;
        allowed_methods GET POST;
    }
}
