server {
	listen 8080;

	root /home/ihajji/github/http-server/www/;
	index index.html;
	client_max_body_size 1000;

	error_page 400 /errors/400.html/;
	error_page 403 /errors/403.html/;
	error_page 404 /errors/404.html/;
	error_page 405 /errors/405.html/;
	error_page 500 /errors/500.html/;

# basic static serving + DELETE
	location / {
		allowed_methods GET DELETE;
		index index.html;
	}

# POST only — tests method restriction
	location /post-only/ {
		allowed_methods POST;
	}

	location /session/ {
		allowed_methods GET;
	}

# directory listing enabled
	location /listing/ {
		allowed_methods GET;
		autoindex on;
	}

	location /no-listing/ {
		allowed_methods GET;
		autoindex off;
	}

# file upload
	location /upload/ {
		allowed_methods GET POST DELETE;
		autoindex on;
	}

	location /post-only/ {
		allowed_methods POST ;
	}

	location /old/ {
		allowed_methods GET;
		return 301 /;
	}

# CGI
	location /cgi-bin/ {
		allowed_methods GET POST;
	root /home/ihajji/github/http-server/www/cgi-bin/;
		cgi .py /usr/bin/python3;
	}
}
