server {
    listen 8081;
    root ./www;

    error_page 404 ./www/errors/404.html;
    error_page 500 ./www/errors/500.html;

    location / {
        methods GET;
    }

    # this route only allows GET — POST returns 405
    # if 405 has no custom page, server must use built-in default
    location /get-only {
        methods GET;
    }
}
