server {
    listen 8080;
    root ./www;
    index index.html;

    location / {
        methods GET;
    }
}

server {
    listen 9090;
    root ./www;
    index about.html;

    location / {
        methods GET;
    }
}

server {
    listen 7070;
    root ./www;
    client_max_body_size 1k;    # tiny limit — tests 413 response

    location / {
        methods GET POST;
    }
}
